version: "3.1"
name: ugc-posters-alerts

services:
  ugc-posters-alerts-cron:
    container_name: ugc-posters-alerts-cron
    image: registry.diikstra.fr/ugc-poster-alerts-cron
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped